---
title: Michelle Kelly Style
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://michellekellystyle.com
description: London-based interior design studio
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- bower_components
- config.codekit3
- CHANGELOG.md
- LICENSE.md
- bower.json
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Michelle Kelly
email: info@michellekellystyle.com
google_site_verification: IAgMKxo_xZJauaD5LGwByTtp3HZHLiLvFhLpSZfNrsY
analytics: UA-96956025-1
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: 
  instagram: 
  twitter: 
  vimeo: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
