enableVersioning: true
handle: press
name: Press
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 00fad3e4-f109-4d06-97b9-f085f15f0928
type: structure
